from .equivalence_relation_interface import EquivalenceRelationInterface
from .subject_relation import SubjectRelation
from .wn_sense_relation import WnSenseRelation
from .taxonomy import Taxonomy
from .taxonomy_builder import TaxonomyBuilder
from .webisalod_taxonomy_builder import WebisalodTaxonomyBuilder
from .wordnet_taxonomy_builder import WordnetTaxonomyBuilder
from .conceptnet_taxonomy_builder import ConceptNetTaxonomyBuilder
